### ISSUE TITLE
Visual Identity Assets for Release

### ISSUE THREAD

**Issue by lllwvlvwlll** [Moonlight-io/visual-identity#6]
This issue updates our social platform assets to properly reflect the brand.
@0ben0 could you take point on this one?

**Comment by 0ben0** [comment]
@anfn101 

[Facebook_Assets.zip](https://github.com/Moonlight-io/visual-identity/files/4251182/Facebook_Assets.zip)
[LinkedIn_Assets.zip](https://github.com/Moonlight-io/visual-identity/files/4251183/LinkedIn_Assets.zip)
[Medium_Assets.zip](https://github.com/Moonlight-io/visual-identity/files/4251185/Medium_Assets.zip)
[Reddit_Assets.zip](https://github.com/Moonlight-io/visual-identity/files/4251186/Reddit_Assets.zip)
[Twitter_Assets.zip](https://github.com/Moonlight-io/visual-identity/files/4251187/Twitter_Assets.zip)

**Comment by anfn101** [comment]
Need revised images for Reddit mobile: 

header should have 10:3 aspect ratio. PNG or JPG only. minimum size: 640x192px / maximum size: 1280x384px

icon must be 256x256 pixels. PNG or JPG only.

For Reddit desktop, the image does not work at all with a logo, since you see both the "Moonlight" homepage logo and the background image also displaying "Moonlight", which is a bit messy looking. The resolution should be at least 1600px by 200px if we want the full image to be seen as well. 

The background image should instead leave space for the subreddit homepage redirect logo to be displayed in the center.

**Comment by anfn101** [comment]
Twitter and Facebook look fine. Please check Medium and LinkedIn to make sure you are ok with those. Reddit needs revised assets, see above. @0ben0

**Comment by lllwvlvwlll** [comment]
@anfn101 twitter looks ok to me; can we update the description as well so it aligns?

**Comment by anfn101** [comment]
Done.

**Comment by lllwvlvwlll** [comment]
Reassigning to @0ben0 per @anfn101's needs.  In the future, @anfn101 could you please reassign to make the intent clear?

**Comment by 0ben0** [comment]
@anfn101 :

> Need revised images for Reddit mobile:
> 
> header should have 10:3 aspect ratio. PNG or JPG only. minimum size: 640x192px / maximum size: 1280x384px

This image is 1280x384:
<img width="871" alt="image" src="https://user-images.githubusercontent.com/35338801/75556773-bc2cae00-5a36-11ea-8adb-e36b145671f0.png">

If the size is good but the graphics need tweaking, please let me know! :)

> icon must be 256x256 pixels. PNG or JPG only.

![Reddit_Subreddit Icon_256x256](https://user-images.githubusercontent.com/35338801/75557012-31987e80-5a37-11ea-95bd-abad7bdd5c24.png)

> For Reddit desktop, the image does not work at all with a logo, since you see both the "Moonlight" homepage logo and the background image also displaying "Moonlight", which is a bit messy looking. The resolution should be at least 1600px by 200px if we want the full image to be seen as well.

![Reddit_Desktop-Banner_1600x200](https://user-images.githubusercontent.com/35338801/75559819-0e240280-5a3c-11ea-96cc-d1d0a923f91f.png)

**Comment by anfn101** [comment]
For the reddit mobile banner, can I get the image without the outside stuff that says the dimensions at the top?

Subreddit icon is ok.

As for the new desktop header, I'm not sure if it works...

See attached: 
![Untitled](https://user-images.githubusercontent.com/26677979/75585873-17fc3480-5a41-11ea-97c6-399c799abaa9.png)

**Comment by 0ben0** [comment]
> For the reddit mobile banner, can I get the image without the outside stuff that says the dimensions at the top?

In the .zip archive 🙂👍

**Comment by 0ben0** [comment]
> As for the new desktop header, I'm not sure if it works...
> 
> See attached:
> ![Untitled](https://user-images.githubusercontent.com/26677979/75585873-17fc3480-5a41-11ea-97c6-399c799abaa9.png

Not sure where the moonlight logo is coming from in that grab? It’s not in any of the supplied assets. Have you added it in @anfn101 ?

**Comment by anfn101** [comment]
The mobile banner is not in the revised asset archive, just the logo, subreddit icon, and desktop banner. Moonlight logo for reddit is in the revised asset archive.

**Comment by 0ben0** [comment]
It was in the original asset archive, sorry for the confusion.

Subreddit assets now modified and live:
![Reddit_Desktop-Banner_1600x200](https://user-images.githubusercontent.com/35338801/75683182-91d52d80-5c8e-11ea-8c01-405a7514641c.png)

![Reddit_Mobile-Banner_1600x480](https://user-images.githubusercontent.com/35338801/75683187-939ef100-5c8e-11ea-9fe5-d679b4f9df61.png)

**Comment by anfn101** [comment]
Can I get a version of both without "Be seen at your best" as well?

Also - hex code for the gray in the ML logo and navy used in above text would also be helpful, thanks

**Comment by 0ben0** [comment]
> Can I get a version of both without "Be seen at your best" as well?

Can I ask why you want to change it? Without the strap-line the illustration doesn't have any context so I'd prefer not to use a plain header.

> Also - hex code for the gray in the ML logo and navy used in above text would also be helpful, thanks

Icon grey - #9496AA
Text navy - #31334A

**Comment by 0ben0** [comment]
Banners for old Reddit, @anfn101 👍 

**DESKTOP:**
![Old-Reddit_Desktop-Banner_1600x200](https://user-images.githubusercontent.com/35338801/76001160-943cbf00-5efc-11ea-8f10-0838a4cefb44.png)

**MOBILE:**
![Old-Reddit_Mobile-Banner_1600x480](https://user-images.githubusercontent.com/35338801/76001168-969f1900-5efc-11ea-9989-6ab012ac5ea4.png)

**Comment by anfn101** [comment]
Old reddit is complete. All should be done now.
